// ============================================================
// SPRICHMIT V2.0 — UI-SPRACHEN (deutsch + türkisch)
// UI-Sprache = Muttersprache des Users
// ============================================================

const LANG = {

  tr: {
    "login.welcome": "🇩🇪 Almancayı öğrenmeye başla!",
    "login.sub": "Ücretsiz ve online — ilerlemen otomatik kaydedilir.",
    "login.email": "E-posta",
    "login.password": "Şifre",
    "login.submit": "Giriş Yap",
    "login.title": "Tekrar hoş geldin! 👋",
    "login.newuser": "Yeni misin? → Kayıt Ol",
    "login.haveacc": "Zaten hesabın var? ← Giriş Yap",
    "login.forgot": "Şifreni mi unuttun?",
    "login.forgot.sent": "E-postanı kontrol et! Sana bir sıfırlama linki gönderdik (spam klasörüne bak!).",
    "login.invalid": "E-posta veya şifre yanlış.",
    "login.exists": "Bu e-posta zaten kayıtlı — lütfen giriş yap.",
    "login.shortpw": "Şifre en az 6 karakter olmalı.",
    "login.signup.title": "Ücretsiz hesap oluştur 🎉",
    "login.signup.ok": "🎉 Hesabın hazır! (E-posta onayı gerekiyorsa önce linki tıkla!) Şimdi giriş yap:",
    "login.registering": "Hesabın oluşturuluyor...",
    "login.registered": "🎉 Hesabın hazır! Şifreni belirle:",
    "login.setPassword": "Şifreyi Kaydet",
    "login.setting": "Kaydediliyor...",
    "login.error": "Hata: {msg}",
    "login.loading": "Yükleniyor...",
    "login.out": "Çıkış",
    "home.hello": "Merhaba {name}! 👋",
    "home.learning": "Sen şu an almanca öğreniyorsun",
    "home.modules.title": "Nasıl ilerlemek istiyorsun?",
    "home.mod.lessons.t": "📚 LERNE",
    "home.mod.lessons.d": "Top-1000 Almanca kelime — 20 derste",
    "home.mod.spelling.t": "✍️ YAZIM",
    "home.mod.spelling.d": "Boşluk doldur, yaz, hatayı bul, büyük/küçük harf",
    "home.mod.grammar.t": "📖 GRAMER",
    "home.mod.grammar.d": "Almanca kuralları adım adım — quiz ile",
    "home.goal.title": "🎯 Bir sonraki hedef",
    "home.streak": "Gün serisi",
    "home.newtoday": "Bugün yeni",
    "home.duetoday": "Bugün tekrar",
    "home.start": "▶ Öğrenmeye Başla",
    "home.startnone": "🎉 Bugün hepsi tamam! Yarın görüşürüz",
    "home.tip": "💡 Her gün aynı saatte çalış, seri (🔥) bozulmasın!",
    "path.title": "📚 Lerne",
    "path.start": "▶ Başla",
    "login.choose": "Öğreneceğin dili seç:",
    "session.learnedcelebr": "🎉 Tebrikler! {n} yeni kelime öğrendin!",
    "session.knownbtn": "😊 Biliyorum",
    "session.zorbtn": "😅 Zor",
    "write.title": "✍️ Yazım",
    "profile.direction": "Hangi dili öğreniyorsun?",
    "profile.dirsaved": "Yön değiştirildi! ⚠️ Her dilin ilerlemesi ayrı saklanır.",
    "path.sub": "Her derste 5 yeni kelime + tekrar. Bitince sonraki ders açılır!",
    "path.locked": "Önce önceki dersi bitir",
    "path.done": "Tamamlandı",
    "session.learn": "YENİ KELİMELER",
    "session.hint": "Kelimeyi oku ve sesi dinle 🎧",
    "session.example": "Örnek",
    "session.continue": "Devam Et",
    "session.new": "Yeni: {n}",
    "session.review": "Tekrar: {n}",
    "session.check": "Kontrol Et",
    "session.choose": "Doğru cevabı seç",
    "session.listen": "🎧 Dinle ve doğru kelimeyi seç",
    "session.write": "Şu kelimeyi yaz: {word}",
    "session.written": "Yazdığın: {ans}",
    "session.correct": "Doğru! 👍",
    "session.wrong": "Yanlış — doğru cevap: {ans}",
    "result.title": "Ders Tamamlandı! 🎉",
    "result.words": "Yeni kelime",
    "result.correct": "Doğru cevap",
    "result.xp": "puan",
    "result.xpbonus": "Hatasız bonus!",
    "result.ago": "Tekrar zamanı",
    "result.review.today": "bugün",
    "result.review.tomorrow": "yarın",
    "result.review.days": "{n} gün sonra",
    "result.back": "← Başa dön",
    "re.title": "✍️ Yazım Kuralları",
    "re.sub": "Bir tip seç. Hataların hatırlatılıp daha sık gösteriliyor!",
    "re.t.luecken": "Boşluk doldur",
    "re.t.luecken.d": "der / die / das, ist / dass ...",
    "re.t.woerter": "Kelime yaz",
    "re.t.woerter.d": "Kelimeyi doğru yaz.",
    "re.t.fehler": "Hataları bul",
    "re.t.fehler.d": "Cümlede TAM 1 hata var. Bul!",
    "re.t.gross": "Büyük / Küçük harf",
    "re.t.gross.d": "Kelime büyük mü küçük mü yazılır?",
    "re.challenge.t": "🎯 Zayıf Noktaların",
    "re.challenge.p": "Sık yanlış yaptığın {n} konu var — hedefli çalış!",
    "re.challenge.btn": "Şimdi çalış",
    "re.none": "Zayıf nokta yok — süpersin! 🎉",
    "re.correct": "Doğru! {ex}",
    "re.wrong": "Yanlış. {ex}",
    "re.cont": "Devam Et →",
    "re.result": "Sonucu Göster",
    "gram.title": "📖 Gramer",
    "gram.sub": "Bir konu seç. Quiz'i hatasız bitirince konu ✅ olur!",
    "gram.mastered": "Tamamlandı",
    "gram.quiz": "🎯 Bu konuya quiz",
    "gram.quizhint": "Yukarıdaki konuyu oku, sonra kendini test et. Hepsini doğru = konu tamamlandı + {p} puan!",
    "gram.masteredmsg": "🏅 Konu tamamlandı! Tüm sorular doğru cevaplandı.",
    "gram.again": "Yine hepsi doğru! (Zaten tamamlanmıştı — Bonus: +5 puan)",
    "gram.fail": "{n} hata yaptın. Konuyu tekrar oku — ✅ için 0 hata gerekli.",
    "res.title": "Bitirildi! 🎉",
    "res.perfect": "Mükemmel! Hepsini doğru — +10 bonus puan!",
    "res.good": "Güzel devam! Yanlışlar aşağıda açıklanıyor.",
    "res.again": "🔁 Tekrar çalış",
    "res.back": "← Geri",
    "profile.title": "👤 Profil",
    "profile.name": "Adın",
    "profile.name.save": "KAYDET",
    "profile.learning": "Şu an almanca öğreniyorsun",
    "profile.lang.tr": "🇹🇷 Türkçe",
    "profile.lang.de": "🇩🇪 Almanca",
    "profile.color": "🎨 Renk",
    "profile.color.blau": "Mavi",
    "profile.color.lila": "Mor",
    "profile.color.orange": "Turuncu",
    "profile.color.gruen": "Yeşil",
    "profile.stats": "İstatistikler",
    "profile.stats.xp": "Puan",
    "profile.stats.streak": "Gün Serisi",
    "profile.stats.words": "Kelime",
    "profile.stats.lessons": "Ders",
    "profile.stats.grammar": "Konu",
    "profile.out": "Çıkış Yap",
    "misc.loading": "Yükleniyor...",
    "misc.saved": "Kaydedildi! ✓",
    "misc.xpt": "+{n} puan! ⭐",
    "misc.badge": "🏅 Rozet: {name} — {hint}",
    "misc.goal.lessons": "🏆 Tüm dersler tamamlansın",
    "misc.goal.lessons.t": "20 dersin hepsini bitir — {n} dersin kaldı.",
    "misc.goal.grammar": "📖 Gramer Ustası Ol",
    "misc.goal.grammar.t": "10 gramer konusunun hepsini hatasız bitir — {n} konu kaldı.",
    "misc.goal.spelling": "✍️ Yazım Ustası Ol",
    "misc.goal.spelling.t": "Toplam 5 yazım turu hatasız çöz — {n} turla kaldı.",
    "misc.goal.xp": "⭐ 500 Puan",
    "misc.goal.xp.t": "İyi cevaplarla 500 puan topla — {n} puan kaldı.",
    "misc.milestones": ["🌟 Harikasın! İlk 10 kelime!", "💪 25 kelime — güzel gidiyorsun!", "🔥 50 kelime — yarı yolda!", "🚀 75 kelime — az kaldı!"],
    "misc.milestoneAll": "🏆 Muhteşem! Tüm kelimeler görüldü — harikasın!"
  },

  de: {
    "login.welcome": "🇹🇷 Türkisch lernen — einfach und spielerisch!",
    "login.sub": "Kostenlos und online — dein Fortschritt wird automatisch gespeichert.",
    "login.email": "E-Mail",
    "login.password": "Passwort",
    "login.submit": "Anmelden",
    "login.title": "Willkommen zurück! 👋",
    "login.newuser": "Neu hier? → Registrieren",
    "login.haveacc": "Schon ein Konto? ← Anmelden",
    "login.forgot": "Passwort vergessen?",
    "login.forgot.sent": "E-Mail-Postfach checken! Wir haben dir einen Reset-Link geschickt (auch Spam-Ordner!).",
    "login.invalid": "E-Mail oder Passwort ist falsch.",
    "login.exists": "Diese E-Mail ist schon registriert — bitte anmelden.",
    "login.shortpw": "Passwort muss mindestens 6 Zeichen haben.",
    "login.signup.title": "Kostenloses Konto erstellen 🎉",
    "login.signup.ok": "🎉 Konto erstellt! (Falls eine E-Mail-Bestätigung nötig war: erst den Link klicken!) Bitte jetzt anmelden:",
    "login.registering": "Konto wird erstellt...",
    "login.registered": "🎉 Konto erstellt! Bitte Passwort festlegen:",
    "login.setPassword": "Passwort speichern",
    "login.setting": "Wird gespeichert...",
    "login.error": "Fehler: {msg}",
    "login.loading": "Lade...",
    "login.out": "Abmelden",
    "home.hello": "Hallo {name}! 👋",
    "home.learning": "Du lernst gerade türkisch",
    "home.modules.title": "Wie möchtest du weitermachen?",
    "home.mod.lessons.t": "📚 LERNEN",
    "home.mod.lessons.d": "Top-1000 Türkische Wörter — in 20 Lektionen",
    "home.mod.spelling.t": "✍️ SCHREIBEN",
    "home.mod.spelling.d": "Lücken füllen, schreiben, Fehler finden, Groß/Klein",
    "home.mod.grammar.t": "📖 GRAMMATIK",
    "home.mod.grammar.d": "Türkische Regeln Schritt für Schritt — mit Quiz",
    "home.goal.title": "🎯 Dein nächstes Ziel",
    "home.streak": "Tage-Serie",
    "home.newtoday": "Neu heute",
    "home.duetoday": "Wiederholen",
    "home.start": "▶ Weiter lernen",
    "home.startnone": "🎉 Alles erledigt für heute — bis morgen!",
    "home.tip": "💡 Arbeite jeden Tag zur gleichen Zeit — behalte deine Serie (🔥)!",
    "path.title": "📚 Lernen",
    "path.start": "▶ Starten",
    "login.choose": "Wähle deine Zielsprache:",
    "session.learnedcelebr": "🎉 Glückwunsch! {n} neue Wörter gelernt!",
    "session.knownbtn": "😊 Ich kenne es",
    "session.zorbtn": "😅 Schwer",
    "write.title": "✍️ Schreiben",
    "profile.direction": "Welche Sprache lernst du?",
    "profile.dirsaved": "Richtung gewechselt! ⚠️ Jeder Fortschritt wird getrennt gespeichert.",
    "path.sub": "Jede Lektion: 5 neue Wörter + Wiederholung. Danach öffnet sich die nächste!",
    "path.locked": "Zuerst die vorherige Lektion abschließen",
    "path.done": "Erledigt",
    "session.learn": "NEUE WÖRTER",
    "session.hint": "Lies das Wort und hör dir die Aussprache an 🎧",
    "session.example": "Beispiel",
    "session.continue": "Weiter",
    "session.new": "Neu: {n}",
    "session.review": "Wiederholung: {n}",
    "session.check": "Prüfen",
    "session.choose": "Wähle die richtige Antwort",
    "session.listen": "🎧 Hör zu und wähle das richtige Wort",
    "session.write": "Schreibe das Wort: {word}",
    "session.written": "Deine Antwort: {ans}",
    "session.correct": "Richtig! 👍",
    "session.wrong": "Leider falsch — richtig war: {ans}",
    "result.title": "Lektion abgeschlossen! 🎉",
    "result.words": "Neue Wörter",
    "result.correct": "Richtige Antworten",
    "result.xp": "Punkte",
    "result.xpbonus": "Bonus ohne Fehler!",
    "result.ago": "Wiederholung in",
    "result.review.today": "heute",
    "result.review.tomorrow": "morgen",
    "result.review.days": "in {n} Tagen",
    "result.back": "← Zurück",
    "re.title": "✍️ Schreibregeln",
    "re.sub": "Wähle einen Typ. Fehler werden gemerkt und öfter gezeigt!",
    "re.t.luecken": "Lücken füllen",
    "re.t.luecken.d": "ben / mi, da / de, -ı / -i ...",
    "re.t.woerter": "Wörter schreiben",
    "re.t.woerter.d": "Schreibe das Wort richtig.",
    "re.t.fehler": "Fehler finden",
    "re.t.fehler.d": "Im Satz ist genau EIN Fehler. Finde ihn!",
    "re.t.gross": "Groß / Klein",
    "re.t.gross.d": "Groß oder klein geschrieben?",
    "re.challenge.t": "🎯 Deine Schwachstellen",
    "re.challenge.p": "Du hast {n} Themen, die du öfter falsch machst — übe gezielt!",
    "re.challenge.btn": "Jetzt üben",
    "re.none": "Keine Schwachstellen — super! 🎉",
    "re.correct": "Richtig! {ex}",
    "re.wrong": "Leider falsch. {ex}",
    "re.cont": "Weiter →",
    "re.result": "Ergebnis anzeigen",
    "gram.title": "📖 Grammatik",
    "gram.sub": "Wähle ein Thema. Alle Quiz-Fragen ohne Fehler = Thema ✅!",
    "gram.mastered": "Meistert",
    "gram.quiz": "🎯 Quiz zu diesem Thema",
    "gram.quizhint": "Lies das Thema, dann teste dich. Alle richtig = Thema gemeistert + {p} Punkte!",
    "gram.masteredmsg": "🏅 Thema gemeistert! Alle Fragen richtig beantwortet.",
    "gram.again": "Alle richtig! (Bereits gemeistert — Bonus: +5 Punkte)",
    "gram.fail": "Du hast {n} Fehler gemacht. Lies das Thema nochmal — der ✅ kommt erst bei 0 Fehlern.",
    "res.title": "Fertig! 🎉",
    "res.perfect": "Perfekt! Alle richtig — +10 Bonuspunkte!",
    "res.good": "Weiter so! Die Fehlerigen sind unten erklärt.",
    "res.again": "🔁 Nochmal üben",
    "res.back": "← Zurück",
    "profile.title": "👤 Profil",
    "profile.name": "Dein Name",
    "profile.name.save": "SPEICHERN",
    "profile.learning": "Du lernst gerade türkisch",
    "profile.lang.tr": "🇹🇷 Türkisch",
    "profile.lang.de": "🇩🇪 Deutsch",
    "profile.color": "🎨 Farbe",
    "profile.color.blau": "Blau",
    "profile.color.lila": "Lila",
    "profile.color.orange": "Orange",
    "profile.color.gruen": "Grün",
    "profile.stats": "Statistik",
    "profile.stats.xp": "Punkte",
    "profile.stats.streak": "Tage",
    "profile.stats.words": "Wörter",
    "profile.stats.lessons": "Lektionen",
    "profile.stats.grammar": "Themen",
    "profile.out": "Abmelden",
    "misc.loading": "Lade...",
    "misc.saved": "Gespeichert! ✓",
    "misc.xpt": "+{n} Punkte! ⭐",
    "misc.badge": "🏅 Badge frei: {name} — {hint}",
    "misc.goal.lessons": "🏆 Alle Lektionen geschafft",
    "misc.goal.lessons.t": "Schließe alle 20 Lektionen ab — noch {n} offen.",
    "misc.goal.grammar": "📖 Grammatik-Ass",
    "misc.goal.grammar.t": "Meistere alle 10 Grammatik-Themen — noch {n} offen.",
    "misc.goal.spelling": "✍️ Schreib-Ass",
    "misc.goal.spelling.t": "Löse insgesamt 5 Schreib-Runden fehlerfrei — noch {n} offen.",
    "misc.goal.xp": "⭐ 500 Punkte",
    "misc.goal.xp.t": "Sammle 500 Punkte — noch {n} Punkte.",
    "misc.milestones": ["🌟 Super! 10 Wörter geschafft!", "💪 25 Wörter — super gemacht!", "🔥 50 Wörter — die Hälfte!", "🚀 75 Wörter — fast geschafft!"],
    "misc.milestoneAll": "🏆 Fantastisch! Alle Wörter gesehen — du rockst das!"
  }
};

// Hilfsfunktion: t("login.welcome") → Text in der UI-Sprache
function t(key, params) {
  const pack = LANG[UI_LANG] || LANG.tr;
  let s = (pack[key] !== undefined) ? pack[key] : (LANG.tr[key] !== undefined ? LANG.tr[key] : key);
  if (params) {
    Object.keys(params).forEach(p => {
      s = s.replace("{" + p + "}", String(params[p]));
    });
  }
  return s;
}